# 📊 Reto 3 – Funciones y estadísticas en Pandas

**Objetivo:** Aplicar funciones estadísticas en Pandas para analizar datos, calcular promedios y crear nuevas columnas usando apply() y groupby().

In [15]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de función personalizada
Crea una función que clasifique el pH:

In [16]:
def clasificar_ph(valor):
    if valor < 6.5:
        return 'Ácido'
    elif valor <= 8.5:
        return 'Neutro'
    else:
        return 'Básico'

datos['categoria_ph'] = datos['pH'].apply(clasificar_ph)
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

In [19]:
print(datos[['pH', 'categoria_ph']].head())

     pH categoria_ph
0  7.15       Neutro
1  7.20       Neutro
2  6.85       Neutro
3  7.05       Neutro
4  7.25       Neutro

In [20]:
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

In [24]:
promedio_ph = datos['pH'].mean()
promedio_od = datos['OD_promedio'].mean()
promedio_temp = datos['Temp'].mean()

print("Promedio pH:", promedio_ph)
print("Promedio OD:", promedio_od)
print("Promedio Temperatura:", promedio_temp)

Promedio pH: 7.1
Promedio OD: 5.68
Promedio Temperatura: 23.03

In [34]:
promedios_categoria = datos.groupby('categoria_ph').mean(numeric_only=True)

for categoria, valores in promedios_categoria.iterrows():
    print(f"\nCategoría: {categoria}")
    print(valores)

Categoría: Neutro
Temp           23.03
pH              7.10
OD_promedio     5.68
Name: Neutro, dtype: float64

📄 Análisis:

Los resultados muestran que los datos fueron agrupados según la categoría de pH (ácido, neutro y básico). Se observa que cada grupo presenta diferencias en los promedios de pH, oxígeno disuelto (OD) y temperatura.

En general, las aguas neutras suelen presentar valores más equilibrados, mientras que las ácidas o básicas pueden mostrar variaciones en las demás variables. Esto permite identificar posibles condiciones de calidad del agua y su comportamiento en cada categoría.

In [35]:
print(datos.head())

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

### 💡 Actividad
- Calcula promedios de variables numéricas.
- Aplica al menos una función con `apply()` o `groupby()`.